#ifndef FIXES_H
#define FIXES_H

#ifdef ALL_FIXES
#  define FIX_APPLY_MASK_SIGNED
#  define FIX_ADD_SIGNED_32
#  define FIX_SUB_SIGNED_32
#  define FIX_ARSH_32EXT_SHL
#  define FIX_ARSH_SIGNED_MASK
#  define FIX_ARSH_UNSIGNED_SIGN
#  define FIX_UMAX_BITS_32
#  define FIX_AND_SIGNED_GUARD
#  define FIX_MUL_UGUARD
#  define FIX_MUL_SCONST
#  define FIX_MUL_SGUARD
#  define FIX_DIVMOD_SIGNED_32
#  define FIX_NEG_SIGNED_32
#  define FIX_FILL_IMM_SIGNED_32
#  define FIX_APPLY_MASK_CONSIST
#  define FIX_NEG_CROSS_INVERT
#  define FIX_ADD_SIGNED_OVFL
#  define FIX_SUB_SIGNED_OVFL
#  define FIX_NEG_ZERO
#  define FIX_ADD_UNSIGNED_OVFL
#  define FIX_ADD_SIGNED_OVFL_OPT
#  define FIX_SUB_UNSIGNED_OVFL
#  define FIX_SUB_SIGNED_OVFL_OPT
#  define FIX_APPLY_MASK_OPT

#endif

#endif
